[machine]
name = "ColecoVision"
id = "COLECO_CV"

[meta]
short-name = "CV"
licensor = "Coleco"
manufacturer = "Coleco"
type = "console"

[meta.na]
release-date = "1982-08"
model-number = ["2400"]

[meta.eu]
model-number = ["6989-8", "6989-8F"]

[input]
groups = ["controller"]

[input.controller]
inputs = ["COLECOVISION_CONTROLLER"]
ports = 4

[[bios]]
name = "coleco.rom"
md5 = ["2c66f5911e5b42b8ebe113403548eee7"]
