[machine]
name = "Xbox 360"
id = "MICROSOFT_X360"

[meta]
short-name = "X360"
licensor = "Microsoft"
manufacturer = "Microsoft"
type = "console"
model-number = ["1439", "1538"]

[meta.na]
release-date = "2005-11-22"

[input]
groups = ["controller", "usb"]

[input.controller]
inputs = ["XBOX_CONTROLLER"]
ports = 4

[input.usb]
accessories = true

[accessories]
class = [
    "disney_infinity",
    "skylander",
    "lego_dimensions",
    "guitar",
    "piano",
    "drums",
    "keyboard",
    "camera",
    "microphone",
    "storage"
]

[storage]
devices = ["hdd", "mu"]

[storage.hdd]
name = "Hard Drive"
user = true

[[storage.hdd.partition]]
id = "system"
name = "System"

[[storage.hdd.partition]]
id = "content"
name = "Content"
user = true

[storage.mu]
name = "Memory Unit"
user = true
