[machine]
name = "TurboGrafx-CD"
id = "NEC_TGCD"

[meta]
short-name = "TGCD"
licensor = "NEC"
manufacturer = "NEC"
type = "console"

[meta.jp]
name = "PC Engine CD"
release-date = "1988-12-04"
model-number = ["CDR-30"]

[meta.na]
model-number = ["HES-CDR-01"]

[input]
groups = ["controller"]

[input.controller]
inputs = ["TG16_CONTROLLER"]
ports = 2

[[bios]]
name = "syscard3.pce"
md5 = ["ff1a674273fe3540ccef576376407d1d", "38179df8f4ac870017db21ebcbf53114", "0754f903b52e3b3342202bdafb13efa5"]

[[bios]]
name = "gecard.pce"
md5 = ["6d2cb14fc3e1f65ceb135633d1694122"]
