[machine]
name = "Nintendo Entertainment System"
id = "NINTENDO_NES"

[meta]
short-name = "NES"
licensor = "Nintendo"
manufacturer = "Nintendo"
type = "console"

[meta.jp]
name = "ファミリーコンピュータ"
name-en = "Family Computer"
model-number = ["HVC-001", "HVC-101"]

[meta.na]
release-date = "1985-10-18"
model-number = ["NES-001", "NES-101"]

[input]
groups = ["controller"]

[input.controller]
inputs = ["NES_CONTROLLER", "FC_MIC_CONTROLLER"]
ports = 2
