[machine]
name = "Nintendo Wii"
id = "NINTENDO_WII"

[meta]
short-name = "Wii"
licensor = "Nintendo"
manufacturer = "Nintendo"
type = "console"

[meta.jp]
release-date = "2006-12-02"

[input]
groups = ["wii", "gamecube", "usb"]

[input.wii]
inputs = ["WII_REMOTE_CONTROLLER", "WII_REMOTE_NUNCHUCK_CONTROLLER"]
ports = 4

[input.gamecube]
inputs = ["GAMECUBE_CONTROLLER"]
ports = 4

[input.usb]
accessories = true
ports = 2

[accessories]
class = [
    "disney_infinity",
    "skylander",
    "keyboard",
    "camera",
    "microphone",
]

[storage]
devices = ["nand", "sd", "slotA", "slotB"]

[storage.nand]
name = "Wii System Storage"

[[storage.nand.partition]]
id = "import"
name = "import"
spec = [
    "NINTENDO_WII/import.mtree",
    "NINTENDO_WII/meta.mtree",
    "NINTENDO_WII/sd.mtree",
    "NINTENDO_WII/shared2.mtree",
    "NINTENDO_WII/sys.mtree",
    "NINTENDO_WII/tmp.mtree",
]

[[storage.nand.partition]]
id = "meta"
name = "meta"
spec = [
    "NINTENDO_WII/import.mtree",
    "NINTENDO_WII/meta.mtree",
    "NINTENDO_WII/sd.mtree",
    "NINTENDO_WII/shared2.mtree",
    "NINTENDO_WII/sys.mtree",
    "NINTENDO_WII/tmp.mtree",
]

[[storage.nand.partition]]
id = "shared1"
name = "shared1"
spec = [
    "NINTENDO_WII/shared1/2.0E.mtree",
    "NINTENDO_WII/shared1/2.1E.mtree",
    "NINTENDO_WII/shared1/2.2E.mtree",
    "NINTENDO_WII/shared1/2.2J.mtree",
    "NINTENDO_WII/shared1/3.0E.mtree",
    "NINTENDO_WII/shared1/3.0J.mtree",
    "NINTENDO_WII/shared1/3.1E.mtree",
    "NINTENDO_WII/shared1/3.1J.mtree",
    "NINTENDO_WII/shared1/3.1U.mtree",
    "NINTENDO_WII/shared1/3.3E.mtree",
    "NINTENDO_WII/shared1/3.3U.mtree",
    "NINTENDO_WII/shared1/3.4E.mtree",
    "NINTENDO_WII/shared1/3.4J.mtree",
    "NINTENDO_WII/shared1/3.4U.mtree",
    "NINTENDO_WII/shared1/4.0J.mtree",
    "NINTENDO_WII/shared1/4.2E.mtree",
    "NINTENDO_WII/shared1/4.2J.mtree",
    "NINTENDO_WII/shared1/4.2K.mtree",
    "NINTENDO_WII/shared1/4.3E.mtree",
    "NINTENDO_WII/shared1/4.3J.mtree",
    "NINTENDO_WII/shared1/4.3K.mtree",
]

[[storage.nand.partition]]
id = "shared2"
name = "shared2"
spec = [
    "NINTENDO_WII/import.mtree",
    "NINTENDO_WII/meta.mtree",
    "NINTENDO_WII/sd.mtree",
    "NINTENDO_WII/shared2.mtree",
    "NINTENDO_WII/sys.mtree",
    "NINTENDO_WII/tmp.mtree",
]

[[storage.nand.partition]]
id = "sys"
name = "sys"
spec = [
    "NINTENDO_WII/import.mtree",
    "NINTENDO_WII/meta.mtree",
    "NINTENDO_WII/sd.mtree",
    "NINTENDO_WII/shared2.mtree",
    "NINTENDO_WII/sys.mtree",
    "NINTENDO_WII/tmp.mtree",
]

[[storage.nand.partition]]
id = "ticket"
name = "ticket"
spec = [
    "NINTENDO_WII/ticket/2.0E.mtree",
    "NINTENDO_WII/ticket/2.0J.mtree",
    "NINTENDO_WII/ticket/2.0U.mtree",
    "NINTENDO_WII/ticket/2.1E.mtree",
    "NINTENDO_WII/ticket/2.2E.mtree",
    "NINTENDO_WII/ticket/2.2J.mtree",
    "NINTENDO_WII/ticket/2.2U.mtree",
    "NINTENDO_WII/ticket/3.0E.mtree",
    "NINTENDO_WII/ticket/3.0J.mtree",
    "NINTENDO_WII/ticket/3.0U.mtree",
    "NINTENDO_WII/ticket/3.1E.mtree",
    "NINTENDO_WII/ticket/3.1J.mtree",
    "NINTENDO_WII/ticket/3.1U.mtree",
    "NINTENDO_WII/ticket/3.3E.mtree",
    "NINTENDO_WII/ticket/3.3J.mtree",
    "NINTENDO_WII/ticket/3.3U.mtree",
    "NINTENDO_WII/ticket/3.4E.mtree",
    "NINTENDO_WII/ticket/3.4J.mtree",
    "NINTENDO_WII/ticket/3.4U.mtree",
    "NINTENDO_WII/ticket/3.5K.mtree",
    "NINTENDO_WII/ticket/4.0E.mtree",
    "NINTENDO_WII/ticket/4.0J.mtree",
    "NINTENDO_WII/ticket/4.1K.mtree",
    "NINTENDO_WII/ticket/4.2E.mtree",
    "NINTENDO_WII/ticket/4.2J.mtree",
    "NINTENDO_WII/ticket/4.2K.mtree",
    "NINTENDO_WII/ticket/4.2U.mtree",
    "NINTENDO_WII/ticket/4.3E.mtree",
    "NINTENDO_WII/ticket/4.3J.mtree",
    "NINTENDO_WII/ticket/4.3K.mtree",
    "NINTENDO_WII/ticket/4.3U.mtree",
]

[[storage.nand.partition]]
id = "title"
name = "title"
spec = [
    "NINTENDO_WII/title/2.0E.mtree",
    "NINTENDO_WII/title/2.0J.mtree",
    "NINTENDO_WII/title/2.0U.mtree",
    "NINTENDO_WII/title/2.1E.mtree",
    "NINTENDO_WII/title/2.2E.mtree",
    "NINTENDO_WII/title/2.2J.mtree",
    "NINTENDO_WII/title/2.2U.mtree",
    "NINTENDO_WII/title/3.0E.mtree",
    "NINTENDO_WII/title/3.0J.mtree",
    "NINTENDO_WII/title/3.0U.mtree",
    "NINTENDO_WII/title/3.1E.mtree",
    "NINTENDO_WII/title/3.1J.mtree",
    "NINTENDO_WII/title/3.1U.mtree",
    "NINTENDO_WII/title/3.2E.mtree",
    "NINTENDO_WII/title/3.2J.mtree",
    "NINTENDO_WII/title/3.2U.mtree",
    "NINTENDO_WII/title/3.3E.mtree",
    "NINTENDO_WII/title/3.3J.mtree",
    "NINTENDO_WII/title/3.3U.mtree",
    "NINTENDO_WII/title/3.4E.mtree",
    "NINTENDO_WII/title/3.4J.mtree",
    "NINTENDO_WII/title/3.4U.mtree",
    "NINTENDO_WII/title/3.5K.mtree",
    "NINTENDO_WII/title/4.0E.mtree",
    "NINTENDO_WII/title/4.0J.mtree",
    "NINTENDO_WII/title/4.0U.mtree",
    "NINTENDO_WII/title/4.1E.mtree",
    "NINTENDO_WII/title/4.1J.mtree",
    "NINTENDO_WII/title/4.1K.mtree",
    "NINTENDO_WII/title/4.1U.mtree",
    "NINTENDO_WII/title/4.2E.mtree",
    "NINTENDO_WII/title/4.2J.mtree",
    "NINTENDO_WII/title/4.2K.mtree",
    "NINTENDO_WII/title/4.2U.mtree",
    "NINTENDO_WII/title/4.3E.mtree",
    "NINTENDO_WII/title/4.3J.mtree",
    "NINTENDO_WII/title/4.3K.mtree",
    "NINTENDO_WII/title/4.3U.mtree",
]

[[storage.nand.partition]]
id = "tmp"
name = "tmp"
spec = [
    "NINTENDO_WII/import.mtree",
    "NINTENDO_WII/meta.mtree",
    "NINTENDO_WII/sd.mtree",
    "NINTENDO_WII/shared2.mtree",
    "NINTENDO_WII/sys.mtree",
    "NINTENDO_WII/tmp.mtree",
]

[storage.sd]
name = "SD Card"
user = true

[[storage.sd.partition]]
id = "sd"
name = "SD Card"
user = true
spec = [
    "NINTENDO_WII/import.mtree",
    "NINTENDO_WII/meta.mtree",
    "NINTENDO_WII/sd.mtree",
    "NINTENDO_WII/shared2.mtree",
    "NINTENDO_WII/sys.mtree",
    "NINTENDO_WII/tmp.mtree",
]

[storage.slotA]
name = "GameCube Memory Card A"
raw = true
user = true

[storage.slotB]
name = "GameCube Memory Card B"
raw = true
user = true
[[bios]]
name = "dsp_rom.bin"
md5 = ["23645d446729a166ab3a9aaba2f5fba5"]

[[bios]]
name = "dsp_coef.bin"
md5 = ["9a6514b88003c9c47e334de654ec550b"]
