[machine]
name = "Atari Lynx"
id = "ATARI_LYNX"

[meta]
short-name = "Lynx"
licensor = "Atari"
manufacturer = "Atari"
type = "handheld"

[meta.na]
release-date = "1989-10-11"
model-number = ["PAG-0201", "PAG-3201", "PAG-0401"]

[meta.eu]
model-number = ["PAG-0200", "PAG-0400"]

[input]
groups = ["layout"]

[input.layout]
inputs = ["LYNX_LAYOUT"]
ports = 1

[[bios]]
name = ["lynxboot.img"]
md5 = "fcd403db69f54290b51035d82f835e7b"
sha1 = "e4ed47fae31693e016b081c6bda48da5b70d7ccb"

[[bios]]
name = ["Atari Lynx BIOS (1989)(Atari).bin"]
md5 = "1a7896e1fe540fe10e51936426b88116"
sha1 = "de60f2263851bbe10e5801ef8f6c357a4bc077e6"
