[machine]
name = "Magnavox Odyssey 2"
id = "MAGNAVOX_O2"

[meta]
short-name = "Odyssey 2"
licensor = "Magnavox"
manufacturer = "Magnavox"
type = "console"

[meta.na]
release-date = "1978"
model-number = ["BA7600 GY02", "BB7600 GY02", "BC7600 GY02", "BC7600 GT02", "BJ7600 GY02", "BK7600 GY02", "CC7600 GY02"]

[meta.eu]
model-number = ["G7000/00", "G7000/20", "G7000/21", "G7000/22", "G7000/30", "G7000/35", "G7000/37", "G7000/53", "G7000/54", "G7000/75"]

[input]
groups = ["controller"]

[input.controller]
inputs = ["MAGNAVOX_O2_CONTROLLER"]
ports = 2

[[bios]]
name = "o2rom.bin"
md5 = ["562d5ebf9e030a40d6fabfc2f33139fd"]

[[bios]]
name = "g7400.bin"
md5 = ["c500ff71236068e0dc0d0603d265ae76"]

[[bios]]
name = "jopac.bin"
md5 = ["279008e4a0db2dc5f1c048853b033828"]

[[bios]]
name = "c52.bin"
md5 = ["f1071cdb0b6b10dde94d3bc8a6146387"]
