[machine]
name = "Xbox Series X|S"
id = "MICROSOFT_XBS"

[meta]
short-name = "XBS"
licensor = "Microsoft"
manufacturer = "Microsoft"
type = "console"
model-number = ["1882", "1883"]

[meta.na]
release-date = "2020-11-10"

[meta.eu]
release-date = "2020-11-10"

[meta.jp]
release-date = "2020-11-10"

[input]
groups = ["controller", "usb"]

[input.controller]
inputs = ["XBOX_CONTROLLER"]
ports = 4

[input.usb]
accessories = true

[accessories]
class = [
    "disney_infinity",
    "skylander",
    "lego_dimensions",
    "guitar",
    "drums",
    "keyboard",
    "mouse",
    "microphone",
    "storage"
]

[storage]
devices = ["ssd", "expansion"]

[storage.ssd]
name = "Internal SSD"

[[storage.ssd.partition]]
id = "temp_content"
name = "Temp Content"

[[storage.ssd.partition]]
id = "user_content"
name = "User Content"
user = true

[[storage.ssd.partition]]
id = "system_support"
name = "System Support"

[[storage.ssd.partition]]
id = "system_update"
name = "System Update"

[[storage.ssd.partition]]
id = "system_update2"
name = "System Update 2"

[[storage.ssd.partition]]
id = "registry"
name = "Registry"

[storage.expansion]
name = "Storage Expansion Card"
user = true
