[machine]
name = "Philips CD-i"
id = "PHILIPS_CDI"

[meta]
short-name = "CD-i"
licensor = "Philips"
manufacturer = "Philips"
type = "console"

[meta.na]
release-date = "1991-12-03"
model-number = ["CDI 910", "CDI 450"]

[meta.eu]
model-number = ["CDI 205", "CDI 210", "CDI 220", "CDI 470", "CDI 490", "CDI 550", "CDI 740", "CDI 310", "CDI 350", "CDI 360", "CDI 370"]

[input]
groups = ["controller"]

[input.controller]
inputs = ["CDI_CONTROLLER"]
ports = 1
accessories = true 

[accessories]
class = [
    "mouse",
    "keyboard"
]

[[bios]]
name = "cdi200.rom"
md5 = ["2969341396aa61e0143dc2351aaa6ef6"]

[[bios]]
name = "cdi220b.rom"
md5 = ["ac0d468be366779c9df633be98da250a"]

[[bios]]
name = "cdi490a.rom"
md5 = ["f0f4e0bf948930b50be8f97730463e34"]

[[bios]]
name = "cdi910.rom"
md5 = ["b69d6553134ad69dfd5ce0ea709b02b5"]
