[machine]
name = "Sega Saturn"
id = "SEGA_SAT"

[meta]
short-name = "Saturn"
licensor = "Sega"
manufacturer = "Sega"
type = "console"

[meta.jp]
release-date = "1994-11-22"
model-number = ["HST-3200", "HST-3210", "HST-3220", "HST-0001"]

[meta.na]
model-number = ["MK-80000", "MK-80000A"]

[meta.eu]
model-number = ["MK-80200-50", "MK-80200A-50"]

[input]
groups = ["controller"]

[input.controller]
inputs = ["SAT_CONTROLLER", "SAT_3D_CONTROLLER"]
ports = 2

[[bios]]
name = "saturn_bios.bin"
md5 = ["af5828fdff51384f99b3c4926be27762"]

[[bios]]
name = "sega_101.bin"
md5 = ["85ec9ca47d8f6807718151cbcca8b964"]

[[bios]]
name = "mpr-17933.bin"
md5 = ["3240872c70984b6cbfda1586cab68dbe"]

[[bios]]
name = "mpr-18811-mx.ic1"
md5 = ["255113ba943c92a54facd25a10fd780c"]

[[bios]]
name = "mpr-19367-mx.ic1"
md5 = ["1cd19988d1d72a3e7caa0b73234c96b4"]

[[bios]]
name = "sega_100.bin"
md5 = ["af5828fdff51384f99b3c4926be27762"]
