[input]
id = "CDI_CONTROLLER"
type = "controller"

[meta]
name = "CD-i Gamepad"
model-number = ["22ER9051", "22ER9019", "22ER9021", "22ER9017"]

[[input.button]]
label = "Button 1"
element = "a"

[[input.button]]
label = "Button 2"
element = "b"

[[input.directional]]
label = "Joystick"
directions = 4
