[input]
id = "NES_CONTROLLER"
type = "controller"

[meta]
name = "NES Controller"

[meta.na]
model-number = ["NES-004", "NES-039"]

[meta.jp]
name = "ファミリーコンピュータ コントローラー"
name-en = "Family Computer Controller"

[[input.button]]
label = "A"
element = "a"

[[input.button]]
label = "B"
element = "b"

[[input.button]]
label = "Start"
element = "start"

[[input.button]]
label = "Select"
element = "select"

[[input.directional]]
label = "D-Pad"
directions = 4
