[input]
id = "TG16_CONTROLLER"
type = "controller"

[meta]
name = "TurboPad"

[meta.na]
model-number = ["HES-PAD-01", "DUO-PAD-01"]

[meta.jp]
model-number = ["PI-PD001", "PI-PD002", "PI-PD6", "PI-PD8", "PCE-TP1", "PCE-TP2"]

[[input.button]]
label = "I"
element = "a"

[[input.button]]
label = "II"
element = "b"

[[input.button]]
label = "Run"
element = "start"

[[input.button]]
label = "Select"
element = "select"

[[input.directional]]
label = "D-Pad"
directions = 4
