[input]
id = "3DS_LAYOUT"
type = "handheld"

[[input.button]]
label = "A"
element = "a"

[[input.button]]
label = "B"
element = "b"

[[input.button]]
label = "Start"
element = "start"

[[input.button]]
label = "Select"
element = "select"

[[input.button]]
label = "L"
element = "l"

[[input.button]]
label = "R"
element = "r"

[[input.directional]]
label = "D-Pad"
directions = 4

[[input.analog]]
axes = 2
alignment = "left"

[[input.analog]]
axes = 2
label = "Circle Pad"
alignment = "right"

[[input.analog]]
axes = 3
class = "gyroscope"

[[input.analog]]
axes = 3
class = "accelerometer"

[[input.touchscreen]]
width = 320
height = 240

[[input.microphone]]
label = "Microphone"

[[input.camera]]
label = "Inner Camera"

[[input.camera]]
label = "Outer Camera (Left)"

[[input.camera]]
label = "Outer Camera (Right)"

[[input.analog]]
label = "3D Slider"
axes = 1
class = "slider"

