[input]
id = "SWITCH_PRO_CONTROLLER"
type = "controller"

[meta]
name = "Nintendo Switch Pro Controller"
model-number = ["HAC-013"]

[meta.jp]
name = "Nintendo Switch Proコントローラー"
name-en = "Nintendo Switch Pro Controller"

[[input.button]]
label = "A"
element = "a"

[[input.button]]
label = "B"
element = "b"

[[input.button]]
label = "X"
element = "x"

[[input.button]]
label = "Y"
element = "y"

[[input.button]]
label = "+"
element = "start"

[[input.button]]
label = "-"
element = "select"

[[input.button]]
label = "Home"
element = "guide"

[[input.button]]
label = "L"
element = "l"

[[input.button]]
label = "R"
element = "r"

[[input.button]]
label = "Capture"
element = "0"

[[input.directional]]
label = "D-Pad"
directions = 4

[[input.analog]]
axes = 2
alignment = "left"

[[input.analog]]
axes = 2
alignment = "right"

[[input.analog]]
axes = 3
class = "gyroscope"

[[input.analog]]
axes = 3
class = "accelerometer"

[[input.trigger]]
label = "ZL"
alignment = "left"
digital = true

[[input.trigger]]
label = "ZR"
alignment = "right"
digital = true

[[input.rumble]]
label = "HD Rumble"
size = "small"
alignment = "left"

[[input.rumble]]
label = "HD Rumble"
size = "small"
alignment = "right"

