[input]
id = "VB_CONTROLLER"
type = "controller"

[meta]
name = "Virtual Boy Controller"
model-number = ["VUE-005"]

[[input.button]]
label = "A"
element = "a"

[[input.button]]
label = "B"
element = "b"

[[input.button]]
label = "Start"
element = "start"

[[input.button]]
label = "Select"
element = "select"

[[input.directional]]
label = "Left D-Pad"
directions = 4
alignment = "left"

[[input.directional]]
label = "Right D-Pad"
directions = 4
alignment = "right"
