[input]
id = "VECTREX_CONTROLLER"
type = "controller"

[meta]
name = "Control Panel"

[[input.button]]
label = "1"
element = "a"

[[input.button]]
label = "2"
element = "b"

[[input.button]]
label = "3"
element = "x"

[[input.button]]
label = "4"
element = "y"

[[input.directional]]
label = "D-Pad"
directions = 4
