[input]
id = "A7800_JOYPAD_CONTROLLER"
type = "controller"

[meta]
name = "Joypad"
model-number = ["CX78"]

[[input.button]]
label = "A"
element = "a"

[[input.button]]
label = "B"
element = "b"

[[input.directional]]
label = "D-Pad"
directions = 4
