[input]
id = "CDI_MOUSE_CONTROLLER"
type = "controller"

[[input.button]]
label = "Button 1"
element = "a"

[[input.button]]
label = "Button 2"
element = "b"

[[input.pointer]]
label = "Cursor"
dimensions = 2
