[input]
id = "DC_CONTROLLER"
type = "controller"

[meta]
name = "Dreamcast Controller"

[meta.na]
model-number = ["HKT-7700"]

[meta.eu]
model-number = ["HKT-7700"]

[meta.jp]
name = "ドリームキャスト コントローラ"
name-en = "Dreamcast Controller"
model-number = ["HKT-7701"]

[[input.button]]
label = "A"
element = "a"

[[input.button]]
label = "B"
element = "b"

[[input.button]]
label = "X"
element = "x"

[[input.button]]
label = "Y"
element = "y"

[[input.button]]
label = "Start"
element = "start"

[[input.directional]]
label = "D-Pad"
directions = 4

[[input.analog]]
axes = 2
alignment = "left"
