[input]
id = "DUALSHOCK_3_CONTROLLER"
type = "controller"

[[input.button]]
label = "Cross"
element = "a"
analog = true

[[input.button]]
label = "Circle"
element = "b"
analog = true

[[input.button]]
label = "Square"
element = "x"
analog = true

[[input.button]]
label = "Triangle"
element = "y"
analog = true

[[input.button]]
label = "Start"
element = "start"

[[input.button]]
label = "Select"
element = "select"

[[input.button]]
label = "L1"
element = "l"

[[input.button]]
label = "R1"
element = "r"

[[input.button]]
label = "L3"
element = "clickl"

[[input.button]]
label = "R3"
element = "clickr"

[[input.button]]
label = "PS Button"
element = "guide"

[[input.directional]]
label = "D-Pad"
hats = 4

[[input.analog]]
axes = 2
alignment = "left"

[[input.analog]]
axes = 2
alignment = "right"

[[input.analog]]
axes = 3
alignment = "gyroscope"

[[input.analog]]
axes = 3
alignment = "accelerometer"

[[input.trigger]]
label = "L2"
alignment = "left"

[[input.trigger]]
label = "R2"
alignment = "right"

[[input.rumble]]
label = "Strong Rumble"
size = "big"

[[input.rumble]]
label = "Weak Rumble"
size = "small"
