[input]
id = "GEN6_CONTROLLER"
type = "controller"

[meta]
name = "6 Button Arcade Pad"

[meta.na]
model-number = ["MK-1653"]

[meta.eu]
model-number = ["MK-1653"]

[meta.jp]
name = "ファイティングパッド6B"
name-en = "Fighting Pad 6B"
model-number = ["SJ-6000"]

[[input.button]]
label = "A"
element = "a"

[[input.button]]
label = "B"
element = "b"

[[input.button]]
label = "C"
element = "c"

[[input.button]]
label = "X"
element = "x"

[[input.button]]
label = "Y"
element = "y"

[[input.button]]
label = "Z"
element = "z"

[[input.button]]
label = "Start"
element = "start"

[[input.button]]
label = "Select"
element = "select"

[[input.directional]]
label = "D-Pad"
directions = 4
