[input]
id = "PCFX_CONTROLLER"
type = "controller"

[meta]
name = "PC-FX Controller"

[[input.button]]
label = "I"
element = "a"

[[input.button]]
label = "II"
element = "b"

[[input.button]]
label = "III"
element = "c"

[[input.button]]
label = "IV"
element = "x"

[[input.button]]
label = "V"
element = "y"

[[input.button]]
label = "VI"
element = "z"

[[input.button]]
label = "Run"
element = "start"

[[input.button]]
label = "Select"
element = "select"

[[input.button]]
label = "MODE 1"
element = "0"

[[input.button]]
label = "MODE 2"
element = "1"

[[input.directional]]
label = "D-Pad"
directions = 4
