[input]
id = "SAT_CONTROLLER"
type = "controller"

[meta]
name = "Control Pad"

[meta.na]
model-number = ["MK-80100"]

[meta.eu]
model-number = ["MK-80301", "MK-80313"]

[meta.jp]
name = "コントロールパッド"
name-en = "Control Pad"
model-number = ["HSS-0101"]

[[input.button]]
label = "A"
element = "a"

[[input.button]]
label = "B"
element = "b"

[[input.button]]
label = "C"
element = "c"

[[input.button]]
label = "X"
element = "x"

[[input.button]]
label = "Y"
element = "y"

[[input.button]]
label = "Z"
element = "z"

[[input.button]]
label = "L"
element = "l"

[[input.button]]
label = "R"
element = "r"

[[input.button]]
label = "Start"
element = "start"

[[input.directional]]
label = "D-Pad"
directions = 4
