[input]
id = "SG1000_CONTROLLER"
type = "controller"

[meta]
name = "SG-1000 Controller"
model-number = ["SJ-200", "SJ-150", "SJ-151", "SJ-300", "SJ-300M"]

[[input.button]]
label = "Fire 1"
element = "a"

[[input.button]]
label = "Fire 2"
element = "b"

[[input.directional]]
label = "Joystick"
directions = 4
