[input]
id = "SMS_CONTROLLER"
type = "controller"

[meta]
name = "Control Pad"
model-number = ["3020"]

[meta.jp]
name = "コントロールパッド"
name-en = "Control Pad"
model-number = ["SJ-152"]

[[input.button]]
label = "1"
element = "a"

[[input.button]]
label = "2"
element = "b"

[[input.directional]]
label = "D-Pad"
directions = 4
