[input]
id = "SWITCH_2_RIGHT_JOYCON_CONTROLLER"
type = "controller"

[meta]
name = "Joy-Con 2 (R)"
model-number = ["BEE-014"]

[[input.button]]
label = "A"
element = "a"

[[input.button]]
label = "B"
element = "b"

[[input.button]]
label = "X"
element = "x"

[[input.button]]
label = "Y"
element = "y"

[[input.button]]
label = "+"
element = "start"

[[input.button]]
label = "Home"
element = "guide"

[[input.button]]
label = "R"
element = "r"

[[input.button]]
label = "SL"
element = "0"

[[input.button]]
label = "SR"
element = "1"

[[input.button]]
label = "C"
element = "2"

[[input.directional]]
label = "D-Pad"
directions = 4

[[input.analog]]
axes = 2
alignment = "right"

[[input.analog]]
axes = 3
class = "gyroscope"

[[input.analog]]
axes = 3
class = "accelerometer"

[[input.trigger]]
label = "ZR"
alignment = "right"
digital = true

[[input.rumble]]
label = "HD Rumble"
size = "small"

[[input.pointer]]
label = "Mouse"
dimensions = 2
