[input]
id = "SWITCH_2_JOYCONS_CONTROLLER"
type = "controller"

[meta]
name = "Joy-Con 2 (L)/(R)"
model-number = ["BEE-012", "BEE-014"]

[[input.button]]
label = "A"
element = "a"

[[input.button]]
label = "B"
element = "b"

[[input.button]]
label = "X"
element = "x"

[[input.button]]
label = "Y"
element = "y"

[[input.button]]
label = "+"
element = "start"

[[input.button]]
label = "-"
element = "select"

[[input.button]]
label = "Home"
element = "guide"

[[input.button]]
label = "Capture"
element = "0"

[[input.button]]
label = "C"
element = "1"

[[input.button]]
label = "L"
element = "l"

[[input.button]]
label = "R"
element = "r"

[[input.directional]]
label = "D-Pad"
directions = 4

[[input.analog]]
axes = 2
alignment = "left"

[[input.analog]]
axes = 2
alignment = "right"

[[input.analog]]
axes = 3
class = "gyroscope"

[[input.analog]]
axes = 3
class = "accelerometer"

[[input.trigger]]
label = "ZL"
alignment = "left"
digital = true

[[input.trigger]]
label = "ZR"
alignment = "right"
digital = true

[[input.rumble]]
label = "HD Rumble"
size = "small"
alignment = "left"

[[input.rumble]]
label = "HD Rumble"
size = "small"
alignment = "right"

[[input.pointer]]
label = "Mouse"
dimensions = 2
alignment = "left"

[[input.pointer]]
label = "Mouse"
dimensions = 2
alignment = "right"

