[input]
id = "SWITCH_2_LEFT_JOYCON_CONTROLLER"
type = "controller"

[meta]
name = "Switch 2 Left Joy-Con"
model-number = ["BEE-012"]

[[input.button]]
label = "-"
element = "select"

[[input.button]]
label = "L"
element = "l"

[[input.button]]
label = "SL"
element = "0"

[[input.button]]
label = "SR"
element = "1"

[[input.button]]
label = "Capture"
element = "guide"

[[input.directional]]
label = "D-Pad"
directions = 4

[[input.analog]]
axes = 2
alignment = "left"

[[input.analog]]
axes = 3
alignment = "gyroscope"

[[input.analog]]
axes = 3
alignment = "accelerometer"

[[input.trigger]]
label = "ZL"
alignment = "left"
digital = true

[[input.rumble]]
label = "HD Rumble"
size = "small"

[[input.pointer]]
label = "Mouse"
dimensions = 2
