[input]
id = "XBOX_CONTROLLER"
type = "controller"

[[input.button]]
label = "A"
element = "a"

[[input.button]]
label = "B"
element = "b"

[[input.button]]
label = "X"
element = "x"

[[input.button]]
label = "Y"
element = "y"

[[input.button]]
label = "Start"
element = "start"

[[input.button]]
label = "Select"
element = "select"

[[input.button]]
label = "L1"
element = "l"

[[input.button]]
label = "R1"
element = "r"

[[input.button]]
label = "L3"
element = "clickl"

[[input.button]]
label = "R3"
element = "clickr"

[[input.button]]
label = "Guide"
element = "guide"

[[input.directional]]
label = "D-Pad"
hats = 4

[[input.analog]]
axes = 2
alignment = "left"

[[input.analog]]
axes = 2
alignment = "right"

[[input.trigger]]
label = "L2"
alignment = "left"

[[input.trigger]]
label = "R2"
alignment = "right"

[[input.rumble]]
label = "Strong Rumble"
size = "big"

[[input.rumble]]
label = "Weak Rumble"
size = "small"
