[package]
authors = [
    "Arne Beer <contact@arne.beer>",
    "David Runge <dvzrv@archlinux.org>",
    "Jagoda Ślązak <j-g00da@archlinux.org>",
    "Orhun Parmaksız <orhun@archlinux.org>",
]
description = "Library and command line interface for the parsing and writing of ALPM-MTREE files"
edition = "2024"
homepage = "https://github.com/SnowflakePowered/consolespec"
keywords = ["alpm", "arch", "linux", "packaging"]
license = "Apache-2.0 OR MIT"
name = "consolespec-mtree"
readme = "README.md"
repository = "https://github.com/SnowflakePowered/consolespec"
rust-version = "1.94"
version = "0.3.3"

[[bin]]
name = "consolespec-mtree"
path = "src/main.rs"
required-features = ["cli"]

[features]
_winnow-debug = ["winnow/debug"]
cli = ["dep:clap", "dep:serde_json"]
creation = ["dep:which"]
default = ["creation"]

[dependencies]
alpm-common = "0.2.1"
alpm-parsers = "0.4.1"
alpm-types = "0.11.2"
clap = { version = "4.5.19", features = ["derive", "env", "string", "wrap_help"], optional = true }
flate2 = "1"
fluent-i18n = "0.1.0"
log = "0.4.27"
serde = { version = "1.0", features = ["derive"] }
serde_json = { version = "1.0", optional = true }
strum = { version = "0.28.0", features = ["derive"] }
thiserror = "2.0.0"
which = { version = "8.0.0", optional = true }
winnow = "0.7.9"

[dev-dependencies]
assert_cmd = "2.0.11"
filetime = "0.2.25"
insta = { version = "1.40.0", features = ["filters"] }
rstest = "0.26.1"
serde_json = "1.0"
simplelog = "0.12.2"
tempfile = "3"
testresult = "0.4.1"

[lints.rust]
missing_debug_implementations = "deny"
missing_docs = "deny"
unsafe_code = "deny"

[lints.clippy]
enum_variant_names = "deny"
