[package]
name = "consolespec"
version = "0.0.1"
edition = "2024"
license = "MIT OR Apache-2.0"
rust-version = "1.94"
build = "build.rs"
description = "Game console specification database"

[features]
default = []
partition-specs = []
partition-spec-digests = ["partition-specs"]

[dependencies]
phf = "0.14"
serde = { version = "1.0", features = ["derive"] }

[build-dependencies]
consolespec-mtree = { path = "../consolespec-mtree", version = "0.4.0", default-features = false }
phf_codegen = "0.14"
serde = { version = "1.0", features = ["derive"] }
string-interner = { version = "0.20", default-features = false, features = ["std", "backends"] }
toml = "0.9"

[lints.rust]
unsafe_op_in_unsafe_fn = "deny"
