[machine]
name = "Vectrex"
id = "GCE_VECTREX"

[meta]
short-name = "Vectrex"
licensor = "General Computer"
manufacturer = "General Computer"
type = "console"

[meta.na]
release-date = "1982-11"
model-number = ["HP-3000", "3000"]

[meta.eu]
model-number = ["3000-UI", "3000-G1"]

[input]
groups = ["controller"]

[input.controller]
inputs = ["VECTREX_CONTROLLER"]
ports = 1
