[machine]
name = "Xbox One"
id = "MICROSOFT_XBO"

[meta]
short-name = "XBO"
licensor = "Microsoft"
manufacturer = "Microsoft"
type = "console"
model-number = ["1540", "1681", "1787"]

[meta.na]
release-date = "2013-11-22"

[input]
groups = ["controller", "usb"]

[input.controller]
inputs = ["XBOX_CONTROLLER"]
ports = 4

[input.usb]
accessories = true

[accessories]
class = [
    "disney_infinity",
    "skylander",
    "lego_dimensions",
    "guitar",
    "drums",
    "keyboard",
    "mouse",
    "camera",
    "microphone",
    "storage"
]

[storage]
devices = ["hdd"]

[storage.hdd]
name = "Hard Drive"

[[storage.hdd.partition]]
id = "temp_content"
name = "Temp Content"

[[storage.hdd.partition]]
id = "user_content"
name = "User Content"
user = true

[[storage.hdd.partition]]
id = "system_support"
name = "System Support"

[[storage.hdd.partition]]
id = "system_update"
name = "System Update"

[[storage.hdd.partition]]
id = "system_update2"
name = "System Update 2"

[[storage.hdd.partition]]
id = "registry"
name = "Registry"
