[machine]
name = "Nintendo GameCube"
id = "NINTENDO_GCN"

[meta]
short-name = "GCN"
licensor = "Nintendo"
manufacturer = "Nintendo"
type = "console"
model-number = ["DOL-001", "DOL-101"]

[meta.jp]
release-date = "2001-09-14"

[input]
groups = ["controller"]

[input.controller]
inputs = ["GAMECUBE_CONTROLLER"]
ports = 4

[[bios]]
name = "IPL.bin"
md5 = ["fc924a7c879b661abc37cec4f018fdf3", "0cdda509e2da83c85bfe423dd87346cc", "db92574caab77a7ec99d4605fd6f2450"]

[storage]
devices = ["slotA", "slotB"]

[storage.slotA]
name = "Memory Card A"
raw = true
user = true

[storage.slotB]
name = "Memory Card B"
raw = true
user = true
